services:
  - type: web
    name: whatsapp-bot
    env: python

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      apt-get update && apt-get install -y ffmpeg && gunicorn voice:app
